g discovery-bridge -
u discovery-bridge-collector - "mDNS collector" /nonexistent /usr/sbin/nologin
u discovery-bridge-publisher - "mDNS publisher" /nonexistent /usr/sbin/nologin
m discovery-bridge-collector discovery-bridge
m discovery-bridge-publisher discovery-bridge
