[server]
allow-interfaces=lan0,lan1
use-ipv4=yes
use-ipv6=yes

[publish]
publish-addresses=no
publish-hinfo=no
publish-workstation=no
publish-domain=no
add-service-cookie=no

[reflector]
enable-reflector=no
