apiVersion: v1
kind: Config
clusters:
- name: cluster
  cluster:
    server: https://[2001:db8:2::5]:6443
    certificate-authority: /var/run/discovery-api/ca.crt
contexts:
- name: discovery
  context:
    cluster: cluster
    user: discovery
current-context: discovery
users:
- name: discovery
  user:
    tokenFile: /var/run/discovery-api/token
